[project]
name = "bvhgs"
version = "0.1.0"
description = "3D Gaussian Splatting with BVH optimization in Slang"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "slangpy>=0.23.0",
    "matplotlib>=3.10.1",
    "numpy-quaternion>=2024.0.8",
    "pyglm>=2.8.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "jupyterlab>=4.4.1",
    "pyright>=1.1.400",
    "pytest>=8.3.5",
    "pytest-benchmark>=5.1.0",
]

[tool.uv.sources]
slangpy = { path = "external/slangpy" }

[tool.black]
line-length = 80

[tool.pyright]
include = ["./src"]
pythonVersion = "3.12"
typeCheckingMode = "basic"
reportMissingSuperCall = "warning"
reportInvalidStringEscapeSequence = "error"
reportMissingParameterType = "warning"
reportMissingTypeArgument = "warning"
reportInvalidTypeForm = "warning"
