[project]
name = "bvhgs"
version = "0.1.0"
description = "3D Gaussian Splatting with BVH optimization in Slang"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "slangpy>=0.23.0",
    "matplotlib>=3.10.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyterlab>=4.4.1",
]
