name: Run pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run tests?'
        required: true
        default: 'yes'
        type: choice
        options:
          - yes
          - no

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Run pytest
        run: uv run pytest tests --benchmark-skip --log-cli-level=INFO
